FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install psycopg2-binary

# copy arial.ttf
COPY ./arial.ttf /usr/share/fonts/truetype/arial.ttf
COPY . /app

CMD ["celery", "-A", "common.tasks", "worker", "--loglevel=info", "--concurrency=1"]